<?php
if (!defined('ABSPATH')) { exit; }
require_once plugin_dir_path(__FILE__) . 'vehicles-v2.php';
require_once plugin_dir_path(__FILE__) . 'vehicles-admin.php';

function gb_page_shell($kicker,$title,$intro,$content,$cta_label='Contacteer Garage Barnes',$cta_url='/contact/') {
    $cta_href = (strpos($cta_url,'tel:')===0 || strpos($cta_url,'mailto:')===0 || strpos($cta_url,'http://')===0 || strpos($cta_url,'https://')===0) ? $cta_url : home_url($cta_url);
    ob_start(); ?>
    <main class="gb-page"><section class="gb-page-hero"><div class="gb-shell"><span class="gb-kicker"><?php echo esc_html($kicker); ?></span><h1><?php echo esc_html($title); ?></h1><p><?php echo esc_html($intro); ?></p></div></section><section class="gb-page-content"><div class="gb-shell"><?php echo $content; ?></div></section><section class="gb-page-cta"><div class="gb-shell gb-page-cta-inner"><div><span class="gb-kicker">Garage Barnes · Hamme</span><h2>We helpen u graag verder.</h2></div><a class="gb-button gb-button-green" href="<?php echo esc_url($cta_href); ?>"><?php echo esc_html($cta_label); ?></a></div></section></main><?php
    return ob_get_clean();
}

function gb_auto_service_shortcode(){
    $network=GB_PLUGIN_URL.'assets/img/123-autoservice-logo.png';
    $content='<div class="gb-content-grid"><div><h2>Onderhoud en herstellingen voor alle merken</h2><p>Garage Barnes staat in voor klein en groot onderhoud, herstellingen en technische diagnose. We communiceren duidelijk en voeren geen bijkomende werken uit zonder uw toestemming.</p><div class="gb-service-list"><span>Klein & groot onderhoud</span><span>Mechanische herstellingen</span><span>Motorwissels</span><span>Elektrische diagnose</span><span>Airco</span><span>Banden & batterijen</span><span>Elektrische voertuigen</span><span>Voorbereiding technische keuring</span><span>Vakantiecheck</span><span>Expertisedossiers</span></div></div><aside class="gb-side-card"><img class="gb-page-network-logo" src="'.esc_url($network).'" alt="1,2,3 AutoService"><h3>Persoonlijke garageservice</h3><p>Een lokaal aanspreekpunt met technische kennis, snelle service en transparante communicatie.</p><a href="tel:+3252570557">+32 52 57 05 57</a></aside></div>';
    return gb_page_shell('Auto Service','Uw wagen in goede handen','Onderhoud, diagnose en herstellingen voor alle merken vanuit onze garage in Hamme.',$content,'Maak een afspraak','/contact/');
}
add_shortcode('garage_barnes_auto_service','gb_auto_service_shortcode');

function gb_towing_shortcode(){
    $base=GB_PLUGIN_URL.'assets/img/takeldienst/';
    $logo=GB_PLUGIN_URL.'assets/img/takeldienst-barnes-logo-wit.png';
    $hero=$base.'IMG_2172.jpeg'; $recovery=$base.'IMG_2638.jpeg'; $action=$base.'IMG_5230.jpeg'; $fleet=$base.'IMG_6662.JPG';
    ob_start(); ?>
    <main class="gb-towing-page">
      <section class="gb-towing-hero" style="background-image:linear-gradient(90deg,rgba(13,13,13,.91) 0%,rgba(13,13,13,.72) 47%,rgba(13,13,13,.24) 100%),url('<?php echo esc_url($hero); ?>')"><div class="gb-shell gb-towing-hero-inner"><img src="<?php echo esc_url($logo); ?>" alt="Takeldienst Barnes 24/7" class="gb-towing-hero-logo"><span class="gb-eyebrow">Takeldienst Hamme · 24/7 bereikbaar</span><h1>Pech of ongeval?<br>Wij komen helpen.</h1><p>Takeldienst Barnes staat dag en nacht klaar voor pechverhelping, depannage, takeling en berging in Hamme en de ruime omgeving.</p><div class="gb-towing-hero-actions"><a class="gb-button gb-button-green" href="tel:+32477353547">Bel +32 477 35 35 47</a><span>24 uur per dag · 7 dagen per week</span></div></div></section>
      <section class="gb-towing-intro"><div class="gb-shell gb-towing-intro-grid"><div><span class="gb-kicker">Snel ter plaatse</span><h2>Takeldienst voor particulieren én professionele partners</h2><p>Sta je met pech langs de weg, start je wagen niet meer of ben je betrokken bij een ongeval? Ook als particulier kun je Takeldienst Barnes rechtstreeks bellen. We zorgen voor een snelle en professionele interventie en bekijken ter plaatse wat nodig is.</p><p>Daarnaast werken we samen met <strong>verzekeraars en bijstandsbedrijven</strong> voor interventies, takelingen en bergingen. Dankzij onze eigen takelwagens en technische ervaring kunnen we uiteenlopende situaties veilig en efficiënt aanpakken.</p></div><aside class="gb-towing-phone-card"><span>Direct hulp nodig?</span><strong>24/7</strong><a href="tel:+32477353547">+32 477 35 35 47</a><small>Rechtstreeks Takeldienst Barnes</small></aside></div></section>
      <section class="gb-towing-services"><div class="gb-shell"><div class="gb-section-heading"><span class="gb-kicker">Onze takeldienst</span><h2>Hulp wanneer het nodig is</h2></div><div class="gb-towing-service-grid"><article><span>01</span><h3>Pechverhelping</h3><p>Problemen onderweg? We komen ter plaatse en bekijken of we je meteen weer op weg kunnen helpen.</p></article><article><span>02</span><h3>Depannage &amp; takeling</h3><p>Wanneer verder rijden niet mogelijk of niet verantwoord is, zorgen we voor een professionele takeling.</p></article><article><span>03</span><h3>Berging na ongeval</h3><p>Ook bij een ongeval of moeilijk bereikbare wagen beschikken we over materiaal en ervaring voor een veilige berging.</p></article><article><span>04</span><h3>24/7 interventies</h3><p>Onze takeldienst is dag en nacht bereikbaar voor particulieren, verzekeraars en bijstandsorganisaties.</p></article></div></div></section>
      <section class="gb-towing-feature"><div class="gb-shell gb-towing-feature-grid"><div class="gb-towing-feature-image"><img src="<?php echo esc_url($recovery); ?>" alt="Takeldienst Barnes tijdens een voertuigberging"></div><div class="gb-towing-feature-copy"><span class="gb-kicker">Berging &amp; interventie</span><h2>Ook voor complexere situaties</h2><p>Niet elke interventie is een eenvoudige panne. Bij een ongeval, een voertuig dat moeilijk bereikbaar staat of een situatie waarbij extra bergingsmateriaal nodig is, zoeken we naar een veilige en praktische oplossing.</p><p>Onze ervaring als garage én takeldienst betekent dat we niet alleen kunnen takelen, maar ook technisch kunnen inschatten wat er met het voertuig aan de hand is.</p><a class="gb-button gb-button-dark" href="tel:+32477353547">Bel de takeldienst</a></div></div></section>
      <section class="gb-towing-partners"><div class="gb-shell gb-towing-partners-grid"><div><span class="gb-kicker">Particulier?</span><h2>Je mag ons rechtstreeks bellen.</h2><p>Je hoeft niet via een tussenpersoon te gaan om Takeldienst Barnes te contacteren. Bij panne, pech of ongeval kun je ons rechtstreeks bereiken op ons 24/7-nummer.</p><a href="tel:+32477353547">+32 477 35 35 47</a></div><div><span class="gb-kicker">Professionele partners</span><h2>Verzekeraars &amp; bijstandsbedrijven</h2><p>We voeren ook interventies uit in opdracht van verzekeraars en bijstandsorganisaties. Een lokaal aanspreekpunt, eigen materieel en duidelijke communicatie bij elke opdracht.</p></div></div></section>
      <section class="gb-towing-gallery"><div class="gb-shell"><div class="gb-section-heading"><span class="gb-kicker">Takeldienst Barnes in actie</span><h2>Eigen materieel. Eigen mensen.</h2></div><div class="gb-towing-gallery-grid"><img src="<?php echo esc_url($action); ?>" alt="Takeldienst Barnes tijdens een interventie"><img src="<?php echo esc_url($fleet); ?>" alt="Wagenpark van Takeldienst Barnes in Hamme"></div></div></section>
      <section class="gb-towing-area"><div class="gb-shell"><span class="gb-kicker">Regio Hamme</span><h2>Takeldienst in Hamme en ruime omgeving</h2><p>Vanuit onze vestiging in <strong>9220 Hamme</strong> verzorgen we pechverhelping, depannage en takeldienst in de ruime regio, onder meer richting Moerzeke, Kastel, Dendermonde, Zele, Waasmunster, Lokeren, Buggenhout, Lebbeke, Temse en Sint-Niklaas. Zit je buiten deze plaatsen? Bel ons gerust: we bekijken meteen wat mogelijk is.</p><a class="gb-button gb-button-green" href="tel:+32477353547">24/7 · +32 477 35 35 47</a></div></section>
    </main><?php return ob_get_clean();
}
add_shortcode('garage_barnes_takeldienst','gb_towing_shortcode');

function gb_about_shortcode(){
    $content='<div class="gb-content-grid"><div><h2>Een lokale garage met een eigen verhaal</h2><p>Garage Barnes groeide vanuit passie voor techniek en persoonlijke service. Peter Barnes startte de garage in bijberoep in 2012, ging in 2015 voltijds verder en verhuisde in 2019 naar de KMO-zone ’t Zonneke in Hamme.</p><p>Doorheen de jaren werd het aanbod uitgebreid met een eigen takeldienst, zodat klanten voor onderhoud, herstellingen én pechhulp bij één vertrouwd aanspreekpunt terechtkunnen.</p><h3>Ons team</h3><div class="gb-team-grid"><div><strong>Peter Barnes</strong><span>Oprichter/eigenaar · Onthaal · Technieker · Takelaar</span></div><div><strong>David Barnes</strong><span>Administratie · Boekhouding</span></div><div><strong>Michael Heylen</strong><span>Technieker · Takelaar · Onthaal</span></div></div></div><aside class="gb-side-card"><h3>Garage Barnes BV</h3><p>Zonneke 4<br>9220 Hamme</p><p>Ma–Vr<br>08:30–12:00<br>13:00–18:00<br>Za–Zo gesloten</p></aside></div>';
    return gb_page_shell('Over ons','Garage Barnes','Lokale service, technische kennis en één aanspreekpunt voor uw wagen.',$content);
}
add_shortcode('garage_barnes_over_ons','gb_about_shortcode');

function gb_contact_shortcode(){
    $content='<div class="gb-contact-cards"><div><span>Garage</span><h3>Afspraak & informatie</h3><a href="tel:+3252570557">+32 52 57 05 57</a><a href="mailto:info@garagebarnes.com">info@garagebarnes.com</a></div><div><span>Takeldienst 24/7</span><h3>Pech of ongeval</h3><a href="tel:+32477353547">+32 477 35 35 47</a></div><div><span>Adres</span><h3>Garage Barnes BV</h3><p>Zonneke 4<br>9220 Hamme<br>België</p></div><div><span>Openingsuren</span><h3>Maandag – vrijdag</h3><p>08:30–12:00<br>13:00–18:00<br>Zaterdag–zondag gesloten</p></div></div>';
    $content.='<div class="gb-contact-lower"><div class="gb-contact-form"><span class="gb-kicker">Stuur ons een bericht</span><h2>Contactformulier</h2><form method="post" action="" onsubmit="return false;"><div class="gb-contact-form-row"><label>Naam<input type="text" name="gb_contact_name" autocomplete="name"></label><label>E-mail<input type="email" name="gb_contact_email" autocomplete="email"></label></div><label>Telefoon<input type="tel" name="gb_contact_phone" autocomplete="tel"></label><label>Uw bericht<textarea name="gb_contact_message" rows="6"></textarea></label><button class="gb-button gb-button-dark" type="submit">Bericht verzenden</button><p class="gb-contact-form-note">Het formulier wordt in een volgende stap gekoppeld aan de e-mailverzending.</p></form></div><div class="gb-contact-map"><iframe title="Garage Barnes op Google Maps" src="https://www.google.com/maps?q=Zonneke%204%2C%209220%20Hamme%2C%20Belgium&output=embed" loading="lazy" referrerpolicy="no-referrer-when-downgrade" allowfullscreen></iframe></div></div>';
    return gb_page_shell('Contact','Contacteer Garage Barnes','Voor een afspraak, technische vraag of directe pechhulp vindt u hier alle contactgegevens.',$content,'Bel de garage','tel:+3252570557');
}
add_shortcode('garage_barnes_contact','gb_contact_shortcode');

function gb_cars_shortcode(){
    if (function_exists('gbv2_render_archive')) return gb_page_shell('Tweedehandswagens','Selecteerde tweedehandswagens','Een wisselend aanbod voertuigen van Garage Barnes.',gbv2_render_archive(),'Vraag naar ons aanbod','/contact/');
    return gb_page_shell('Tweedehandswagens','Selecteerde tweedehandswagens','Een wisselend aanbod voertuigen van Garage Barnes.','<div class="gb-empty-state"><h2>Ons voertuigaanbod komt hier.</h2></div>');
}
add_shortcode('garage_barnes_tweedehands','gb_cars_shortcode');

function gb_upgrade_placeholder_pages(){ if(get_option('gb_site_pages_v2_done')) return; $map=array('auto-service'=>'[garage_barnes_auto_service]','takeldienst'=>'[garage_barnes_takeldienst]','tweedehands'=>'[garage_barnes_tweedehands]','over-ons'=>'[garage_barnes_over_ons]','contact'=>'[garage_barnes_contact]'); foreach($map as $slug=>$shortcode){$page=get_page_by_path($slug,OBJECT,'page'); if($page && strpos($page->post_content,'Deze pagina wordt verder opgebouwd')!==false) wp_update_post(array('ID'=>$page->ID,'post_content'=>$shortcode));} update_option('gb_site_pages_v2_done',1,false); }
add_action('init','gb_upgrade_placeholder_pages',30);
